name: akhali
channels:
  - conda-forge
  - iri-nextgen
  - fastai
dependencies:
  # rasterio build fails with python 3.10
  # https://github.com/rasterio/rasterio/issues/2333
  - python=3.9
  - bottleneck
  - cptio
  - dash
  - dash-leaflet
  - dash-bootstrap-components
  - dask-core
  - netcdf4
  - numpy
  - opencv-python-headless
  - pandas=1.3  # To upgrade, use psycopg2 via SLQAlchemy.
  - pip  # for installing/compiling mod_wsgi in Dockerfile
  - psycopg2
  - rasterio
  - scipy
  - shapely
  - werkzeug<2.1  # 2.1 spews warnings at dev server start
  - xarray
  - yaml
  - zarr
